---
title: "My sad story"
date: 2022-04-1
---
theme: minima
author: One sad girl 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is an example of toxic behavior in my friendship with two guys who eat my food, live in my flat and don't give a fuck about my feelings.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepag
